config/routes.rb
BuzzmonitorBlogRails::Application.routes.draw do

  match "/404", :to => "pages#error_404"
  
  get "home" => 'pages#home', :as => :home

  get "home_a" => 'pages#home_a', :as => :home_a

  get "home_b" => 'pages#home_b', :as => :home_b

  get "home_c" => 'pages#home_c', :as => :home_c

  get "ebooks/:slug" => 'ebooks#detail', :as => :detail_ebook

  get "ebooks/e/:slug" => 'ebooks#detail', :as => :detail_ebook

  post "ebook_users" => 'ebooks#register', :as =>  :ebook_register

  get "download/:slug" => "ebooks#download", :as => :download_ebooks

  get "ebooks" => "ebooks#index", :as => :ebooks

  get "blog" => "blog#index", :as => :blog

  get "blog/:slug" => "blog#show", :as => :show_blog

  match "artigos" => "artigos#index", :as => :artigos
  
  match "artigos/:slug" => "artigos#show", :as => :artigo

  match "imprensa" => "imprensa#index", :as => :imprensa
  
  match "imprensa/:slug" => "imprensa#show", :as => :show_imprensa

  get "conheca" => 'pages#conheca', :as => :conheca

  get "ebooks/obrigado/:slug" => "ebooks#thankyou", :as => :thankyou_ebooks

  post "submit_proposal" => 'pages#submit_proposal', :as => :submit_proposal

  post "submit_proposal" => 'pages#submit_proposal', :as => :submit_proposal

  post "submit_newsletter" => 'pages#submit_newsletter', :as => :submit_newsletter

  post "submit_signup" => 'users#submit_signup', :as => :submit_signup

  match "proposal_tks" => "pages#proposal_tks", :as => :proposal_tks

  
  get "/" => 'pages#faq', :constraints => { :subdomain => /faq/ }
  
  ActiveAdmin.routes(self)

  devise_config = ActiveAdmin::Devise.config

  devise_config[:controllers][:passwords] = 'passwords'

  devise_for :admin_users, devise_config

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#home'

end

app/views/partials/_expert.html.erb
<div style="display: none;">

			<div id="expert-box">

				<a id="email" href="mailto:atendimento@elife.com.br">atendimento@elife.com.br</a>

				<div id="share-facebook">

					<iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com/buzzmonitor%2F&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;font=arial&amp;colorscheme=light&amp;action=like&amp;height=21&amp;appId=391485537588224" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:21px;" allowTransparency="true"></iframe>

				</div>

				<div id="share-google-plus">

					<div class="g-plusone" data-size="medium"></div>

				</div>

				<div id="share-twitter">

					<a href="https://twitter.com/share" class="twitter-share-button" data-lang="pt"></a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

				</div>

			</div>

		</div>

app/views/partials/_facebook_pixel.html.erb
<% if !@ebook.nil? && current_page?(:controller => 'ebooks', :action => 'thankyou', :slug => @ebook.slug)  %>

<!-- Facebook Conversion Code for Cadastros Ebooks Buzzmonitor Portugal -->
<script>(function() {
var _fbq = window._fbq || (window._fbq = []);
if (!_fbq.loaded) {
var fbds = document.createElement('script');
fbds.async = true;
fbds.src = '//connect.facebook.net/en_US/fbds.js';
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(fbds, s);
_fbq.loaded = true;
}
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', '6025596583765', {'value':'0.01','currency':'BRL'}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6025596583765&amp;cd[value]=0.01&amp;cd[currency]=BRL&amp;noscript=1" /></noscript>

<% else %>
<script>(function() {
var _fbq = window._fbq || (window._fbq = []);
if (!_fbq.loaded) {
var fbds = document.createElement('script');
fbds.async = true;
fbds.src = '//connect.facebook.net/en_US/fbds.js';
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(fbds, s);
_fbq.loaded = true;
}
_fbq.push(['addPixelId', '447270098765927']);
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', 'PixelInitialized', {}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=447270098765927&amp;ev=PixelInitialized" /></noscript>

<% end %>

app/views/partials/_facebook_remarketing.html.erb
<script>(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
  _fbq.push(['addPixelId', '632265810227199']);
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', 'PixelInitialized', {}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=632265810227199&amp;ev=PixelInitialized" /></noscript>

app/views/partials/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <ul class="footer-nav">
          <li><a href="<%= root_url %>#know"><%= t("menu.understand").downcase %></a></li>
          <li><a href="<%= root_url %>#ebooks"><%= t("menu.ebook").downcase %></li>
          <li><a href="<%= root_url %>#plans"><%= t("menu.plans").downcase %></a></li>
          <li><%= link_to t("menu.blog").downcase, blog_path %></li>
          <li><%= link_to t("menu.press").downcase, imprensa_path %></li>
        </ul>
        <div class="social"><a href="https://www.facebook.com/buzzmonitor" target="_blank" class="fb">Facebook</a><a href="https://twitter.com/buzz_monitor" target="_blank" class="tw">Twitter</a><a href="https://www.youtube.com/Buzzmonitor" target="_blank" class="yt">YouTube</a><a href="http://pt.slideshare.net/Elife2009" target="_blank" class="ss">Slideshare</a></div>
      
      
        <%= form_tag submit_newsletter_path, remote: true, :class => 'news-form'  do  %>
          <fieldset>
            <label for="news-email"><%= t("newsletter.subscribe_to_our_newsletter")%></label>
            <%= text_field(:newsletter, :email, :id => "news-email", :placeholder => t("newsletter.insert_your_email")) %>
            <%= submit_tag "ok", disable_with: t('helpers.submit.waiting') %>
          </fieldset>
        <% end %>
        
      </div>
      <div class="col-md-3"><a href="http://elife.com.br" class="elife">e.life group</a><a href="http://casulloweb.com.br" target="_blank" rel="co-worker" title="Casullo Agência Digital" class="casullo">Casullo Agência Digital</a></div>
    </div>
  </div>
</footer>

app/views/partials/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV['analytics_base'] %>', 'auto');
  ga('send', 'pageview');

</script>

app/views/partials/_google_plus.html.erb
<a href="https://plus.google.com/104579046053578337795" rel="publisher"></a>

app/views/partials/_google_remarketing.html.erb
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 964053005;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/964053005/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

app/views/partials/_header.html.erb
<head>

  <% if !@testeab.nil? && Rails.env.production? %>
    <%= render 'partials/testeab' %>
  <% end %>


  <title><%= @title.nil? ? 'Buzzmonitor, monitorização de redes sociais.' : @title %></title>
  <meta property="description" content="Buzzmonitor: a ferramenta de segunda geração para monitorização de redes sociais, social crm e social analytics."/>
  <meta name="keywords" content="monitoração de mídias sociais, monitorização de mídias socias, big data, big insights">
  <meta name="distribution" content="web">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Buzzmonitor: a ferramenta de segunda geração para monitorização de redes sociais, social crm e social analytics."/>
  <meta http-equiv="Cache-control" content="public">


  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Buzzmonitor">

  <link href="/assets/favicon_tammy_16x16.png" rel="shortcut icon">
  <link href="/assets/favicon_tammy_32x32.png" rel="apple-touch-icon">

<% unless @post.nil? %>

  <meta property="og:title" content="<%= @post.title.to_s %>"/>
  <meta property="og:site_name" content="Buzzmonitor"/>
  <meta property="og:description" content="<%= @post.subtitle.to_s %>" />
  <meta property="og:image" content="<%= @post.cover.url(:home).to_s %>"/>

<% else %>

  <meta property="og:title" content="<%= @title.nil? ? 'Buzzmonitor, monitorização de redes sociais.' : @title %>"/>
  <meta property="og:site_name" content="Buzzmonitor"/>
  <meta property="og:description" content="Buzzmonitor, uma ferramenta muito mais inteligente para monitorar as redes sociais."/>
  <meta property="og:image" content="<%= root_url + 'assets/buzzmonitor.png' %>"/>


<% end %>

  <!-- begin olark code --><script data-cfasync="false" type='text/javascript'>/*{literal}<![CDATA[*/ 
  window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){f[z]=function(){(a.s=a.s||[]).push(arguments)};var a=f[z]._={},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={0:+new Date};a.P=function(u){a.p[u]=new Date-a.p[0]};function s(){a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{b.contentWindow[g].open()}catch(w){c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{var t=b.contentWindow[g];t.write(p());t.close()}catch(x){b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]}); 
  /* custom configuration goes here (www.olark.com/documentation) */ 
  olark.identify('2421-258-10-5310');/*]]>{/literal}*/</script><noscript><a href="https://www.olark.com/site/2421-258-10-5310/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript><!-- end olark code -->

  <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>

  <script type="text/javascript">
    var recaptcha_public_key = '<%= Rails.application.config.recaptcha_public_key %>'
  </script>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

   

    <%= auto_discovery_link_tag(:rss, blog_url(:format => :rss)) %>
    <%= auto_discovery_link_tag(:rss, imprensa_url(:format => :rss)) %>


    <% if current_page?(controller: 'ebooks', action: 'thankyou', slug: 'social-crm-estrategico') %>
      <!-- Facebook Conversion Code for Cadastros para Download de E-books Buzzmonitor -->
      <script>(function() {
        var _fbq = window._fbq || (window._fbq = []);
        if (!_fbq.loaded) {
          var fbds = document.createElement('script');
          fbds.async = true;
          fbds.src = '//connect.facebook.net/en_US/fbds.js';
          var s = document.getElementsByTagName('script')[0];
          s.parentNode.insertBefore(fbds, s);
          _fbq.loaded = true;
        }
      })();
      window._fbq = window._fbq || [];
      window._fbq.push(['track', '6017390962765', {'value':'0.00','currency':'BRL'}]);
      </script>
      <noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6017390962765&amp;cd[value]=0.00&amp;cd[currency]=BRL&amp;noscript=1" /></noscript>
    <% end %>


    <% if !@ebook.try(:slug).nil? && current_page?(controller: 'ebooks', action: 'thankyou', slug: @ebook.slug ) %>
      <%= raw @ebook.script unless @ebook.script.blank? %>
    <% end %>

    <%= render 'partials/facebook_pixel' %>
    <%= render 'partials/google_analytics' %>
</head>

app/views/partials/_login.html.erb
<div class="login-container">
      <div id="login-box" class="login-box">
        <div class="toppy">
          <h2>Login</h2>
        </div>
        <form action="https://app.buzzmonitor.com.br/user/session/" method="post" name="form-login">
          <fieldset>
            <div class="signup"><a href="https://app.buzzmonitor.com.br/user/session/new?provider=facebook" class="signfb">Entre com o Facebook  </a><a href="https://app.buzzmonitor.com.br/user/session/new?provider=twitter" class="signtw">Entre com o Twitter </a><span>ou</span></div>
            <div>
              <label for="username"> <span>Username</span></label>
              <input id="username" type="text" name="username" placeholder="E-mail">
            </div>
            <div>
              <label for="password">Senha</label>
              <input id="password" type="password" name="password" placeholder="Senha">
              <button title="Entrar" class="button">Login</button>
              <p><a href="https://app.buzzmonitor.com.br/user/signup/new" title="Cadastre-se com o email" class="pull-left">Cadastre-se!</a><a href="https://app.buzzmonitor.com.br/user/recoveries/new" title="Clique para receber instruções de como recuperar sua senha" class="pull-right">Esqueceu a senha?</a></p><a href="<%= root_url %>#plans" class="plans"><strong>+</strong> Planos</a>
            </div>
          </fieldset>
        </form>
      </div>
    </div>

app/views/partials/_menu_top.html.erb
<header>
  <nav role="navigation" data-spy="affix" data-offset-top="10" class="navbar">
    <div class="navbar-header"><a href="<%= root_url %>" class="navbar-brand">Buzzmonitor</a>
      <ul class="nav visible-md visible-lg">
        <li><a href="#know"><%= t("menu.understand") %></a></li>
        <li><a href="#ebooks"><%= t("menu.ebook") %></a></li>
        <li><a href="#plans"><%= t("menu.plans") %></a></li>
        <li><%= link_to t("menu.blog"), blog_path %></li>
      </ul>
      <div class="control-links">
        <div class="dropdown visible-xs visible-sm"><a href="#" data-toggle="dropdown" class="toggle-menu">Menu</a>
          <ul role="menu" class="dropdown-menu">
            <li><a href="#know"><%= t("menu.understand") %></a></li>
            <li><a href="#ebooks"><%= t("menu.ebook") %></a></li>
            <li><a href="#plans"><%= t("menu.plans") %></a></li>
            <li><%= link_to t("menu.blog"), blog_path %></li>
            <li><a href="#proposal"><%= t("menu.proposal") %></a></li>
          </ul>
        </div><a href="#proposal" class="hidden-xs hidden-sm proposal"><%= t("menu.proposal") %></a><a href="#login-box" class="login">Login</a>
      </div>
    </div>
  </nav>
</header>

app/views/partials/_menu_top_internal.html.erb
<header>
  <nav class="navbar affix">
    <div class="navbar-header"><a href="<%= root_url %>" class="navbar-brand">Buzzmonitor</a>
      <ul class="nav visible-md visible-lg">
        <li><a href="<%= root_url %>#know"><%= t("menu.understand") %></a></li>
        <li><a href="<%= root_url %>#ebooks"><%= t("menu.ebook") %></li>
        <li><a href="<%= root_url %>#plans"><%= t("menu.plans") %></a></li>
        <li><%= link_to t("menu.blog"), blog_path %></li>
      </ul>
      <div class="control-links">
        <div class="dropdown visible-xs visible-sm"><a href="#" data-toggle="dropdown" class="toggle-menu">Menu</a>
          <ul role="menu" class="dropdown-menu">
            <li><a href="<%= root_url %>#know"><%= t("menu.understand") %></a></li>
            <li><a href="<%= root_url %>#ebooks"><%= t("menu.ebook") %></a></li>
            <li><a href="<%= root_url %>#plans"><%= t("menu.plans") %></a></li>
            <li><%= link_to t("menu.blog"), blog_path %></li>
            <li><a href="<%= root_url %>#proposal"><%= t("menu.proposal") %></a></li>
          </ul>
        </div><a href="<%= root_url %>#proposal" class="hidden-xs hidden-sm proposal"><%= t("menu.proposal") %></a><a href="#login-box" class="login">Login</a>
      </div>
    </div>
  </nav>
</header>

app/views/partials/_proposal.html.erb
 <%- model_class = Proposal -%>
 <%= form_for @proposal, :url => submit_proposal_url, remote: true ,:html => {:class => "form-validate-proposal"} do |f| %>
      <%= hidden_field_tag :proposal_origin, nil %> 

      <fieldset>
        <div class="form-group">
          <%= f.label :name, class: 'text-hide' %>
          <%= f.text_field :name,  :class => '', required: true, placeholder:  model_class.human_attribute_name(:name) %>
        </div>
        <div class="form-group">
          <%= f.label :company_name, class: 'text-hide' %>
          <%= f.text_field :company_name,  :class => '', required: true, placeholder:  model_class.human_attribute_name(:company_name) %>
        </div>
        <div class="form-group">
          <%= f.label :phone_number, class: 'text-hide' %>
          <%= f.text_field :phone_number,  :class => 'telefone', required: true, placeholder:  model_class.human_attribute_name(:phone_number) %>
        </div>
        <div class="form-group">
          <%= f.label :email_address, class: 'text-hide' %>
          <%= f.text_field :email_address,  :class => 'email', required: true, placeholder:  model_class.human_attribute_name(:email_address) %>
        </div>
        <div class="checkbox">
          <label> 
           <%= f.check_box :newsletter, :checked => "checked" %> <%= model_class.human_attribute_name(:accept_proposal) %>
          </label>
        </div>
        <% unless !@proposal_verify_robot %>
          <%= render "partials/recaptcha" %>                  
        <% end %> 
        <%= f.submit t("proposal.submit_button"), class: "btn-send", disable_with: t('helpers.submit.waiting') %> 
      </fieldset>
    <% end -%>

app/views/partials/_recaptcha.html.erb
 <script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>
<div id="general-captcha" class="recaptcha_widget">
 <div class="container-captcha" id="recaptcha_widget_general">
   <div class="imagem" id="recaptcha_image">
   </div>
   <div class="recaptcha_input">
     <label for="recaptcha_response_field" class="recaptcha_only_if_image"><%= t "recaptcha.recaptcha_only_if_image" %>:</label>
     <label for="recaptcha_response_field" class="recaptcha_only_if_audio"><%= t "recaptcha.recaptcha_only_if_audio" %>:</label>
     <input id="recaptcha_response_field" type="text" name="recaptcha_response_field">
   </div>
    <ul class="recaptcha_options">
     <li><a href="javascript:Recaptcha.reload()"><i class="glyphicon glyphicon-refresh"></i><span class="captcha_hide">Outro CAPTCHA</span></a></li>
     <li class="recaptcha_only_if_image"><a href="javascript:Recaptcha.switch_type('audio')"><i class="glyphicon glyphicon-volume-up"></i><span class="captcha_hide">CAPTCHA com audio</span></a></li>
     <li class="recaptcha_only_if_audio"><a href="javascript:Recaptcha.switch_type('image')"><i class="glyphicon glyphicon-picture"></i><span class="captcha_hide">CAPTCHA com imagem</span></a></li>
     <li><a href="javascript:Recaptcha.showhelp()"><i class="glyphicon glyphicon-question-sign"></i><span class="captcha_hide">Ajuda</span></a></li>
   </ul>
 </div>
</div>

app/views/partials/_testeab.html.erb
<!-- Google Analytics Content Experiment code -->
<script>function utmx_section(){}function utmx(){}(function(){var
k='66887058-13',d=document,l=d.location,c=d.cookie;
if(l.search.indexOf('utm_expid='+k)>0)return;
function f(n){if(c){var i=c.indexOf(n+'=');if(i>-1){var j=c.
indexOf(';',i);return escape(c.substring(i+n.length+1,j<0?c.
length:j))}}}var x=f('utmx'),xx=f('utmxx'),h=l.hash;d.write(
'<sc'+'ript src="'+'http'+(l.protocol=='https:'?'s://ssl':
'://www')+'.google-analytics.com/ga_exp.js?'+'utmxkey='+k+
'&utmx='+(x?x:'')+'&utmxx='+(xx?xx:'')+'&utmxtime='+new Date().
valueOf()+(h?'&utmxhash='+escape(h.substr(1)):'')+
'" type="text/javascript" charset="utf-8"><\/sc'+'ript>')})();
</script><script>utmx('url','A/B');</script>
<!-- End of Google Analytics Content Experiment code -->