config/routes.rb
BuzzmonitorBlogRails::Application.routes.draw do

  match "/404", :to => "pages#error_404"
  
  get "home" => 'pages#home', :as => :home

  get "home_a" => 'pages#home_a', :as => :home_a

  get "home_b" => 'pages#home_b', :as => :home_b

  get "home_c" => 'pages#home_c', :as => :home_c

  get "ebooks/:slug" => 'ebooks#detail', :as => :detail_ebook

  get "ebooks/e/:slug" => 'ebooks#detail', :as => :detail_ebook

  post "ebook_users" => 'ebooks#register', :as =>  :ebook_register

  get "download/:slug" => "ebooks#download", :as => :download_ebooks

  get "ebooks" => "ebooks#index", :as => :ebooks

  get "blog" => "blog#index", :as => :blog

  get "blog/:slug" => "blog#show", :as => :show_blog

  match "artigos" => "artigos#index", :as => :artigos
  
  match "artigos/:slug" => "artigos#show", :as => :artigo

  match "imprensa" => "imprensa#index", :as => :imprensa
  
  match "imprensa/:slug" => "imprensa#show", :as => :show_imprensa

  get "conheca" => 'pages#conheca', :as => :conheca

  get "ebooks/obrigado/:slug" => "ebooks#thankyou", :as => :thankyou_ebooks

  post "submit_proposal" => 'pages#submit_proposal', :as => :submit_proposal

  post "submit_proposal" => 'pages#submit_proposal', :as => :submit_proposal

  post "submit_newsletter" => 'pages#submit_newsletter', :as => :submit_newsletter

  post "submit_signup" => 'users#submit_signup', :as => :submit_signup

  match "proposal_tks" => "pages#proposal_tks", :as => :proposal_tks

  
  get "/" => 'pages#faq', :constraints => { :subdomain => /faq/ }
  
  ActiveAdmin.routes(self)

  devise_config = ActiveAdmin::Devise.config

  devise_config[:controllers][:passwords] = 'passwords'

  devise_for :admin_users, devise_config

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#home'

end

app/views/pages/_carrossel.html.erb
  <% unless cookies[:ebook_user].blank?  %>

    <% Ebook.all.each do |ebook| %>
        <%= link_to download_ebooks_path(ebook.slug), remote: @remote_ebook, :target => "_blank", :class => "link-ebook "  do %>
          <%= image_tag ebook.imagem.url(:medium), :alt => ebook.titulo %>
        <% end %>
    <% end %> 

  <% else %>

    <% Ebook.all.each do |ebook| %>
        <%= link_to download_ebooks_path(ebook.slug), remote: @remote_ebook, :target => "_blank", :class => "link-ebook "  do %>
          <%= image_tag ebook.imagem.url(:medium), :alt => ebook.titulo %>
        <% end %>
    <% end %> 

  <% end %>  

</div>

app/views/pages/_know.html.erb
 <section id="know" class="know">
      <div class="container">
        <h2 class="section-title">Conheça o <strong>Buzzmonitor</strong></h2>
        <p class="section-excerpt">O primeiro da sua categoria que permite criar combinações ilimitadas de relatórios e integra quatro funcionalidades numa só plataforma.</p>
        <div class="row">
          <div class="col-sm-3">
            <div class="size">
              <div class="icon-container"><img src="/assets/icons/monitoring.png" data-bottom-top="transform:rotate(-80deg)" data-center-top="transform:rotate(0deg)" alt="Imagem de uma lupa amarela"></div>
              <h4>Monitorização</h4>
              <p>Monitorize a sua marca nas redes sociais. Use o nosso exclusivo Report Engine para criar relatórios customizados para os seus projetos.</p>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="size">
              <div class="icon-container"><img src="/assets/icons/analytics.png" data-bottom-top="transform:scaleY(0); transform-origin: 50% 90%" data-center-top="transform:scaleY(1); transform-origin: 50% 90%" alt="Imagem de barras verticais de tamanhos variados"></div>
              <h4>Social Analytics</h4>
              <p>Faça análises comparativas da performance da sua marca e concorrentes em canais próprios de Facebook, YouTube e Twitter.</p>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="size">
              <div class="icon-container dummys"><img src="/assets/icons/dummy-white.png" data--50-bottom="transform:rotate(-30deg)" data--350-bottom="transform:rotate(30deg)" data-200-top="transform:rotate(0deg)" alt="Imagem de pequeno boneco branco" class="third"><img src="/assets/icons/dummy-white.png" data--50-bottom="transform:rotate(-30deg)" data--350-bottom="transform:rotate(30deg)" data-200-top="transform:rotate(0deg)" alt="Imagem de pequeno boneco branco" class="second"><img src="/assets/icons/dummy-yellow.png" data--50-bottom="transform:rotate(-30deg)" data--350-bottom="transform:rotate(30deg)" data-200-top="transform:rotate(0deg)" alt="Imagem de boneco amarelo" class="first"></div>
              <h4>Social CRM</h4>
              <p>Responda aos seus fãs e seguidores no Facebook e Twitter, classifique conversas e obtenha relatórios sobre essas interações.</p>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="size">
              <div class="icon-container folder"><img src="/assets/icons/folder-white.png" data-bottom-top="top:37px;" data-center-top="top[WTF]:15px" alt="Imagem de pastas de arquivos em sequência" class="third"><img src="/assets/icons/folder-white.png" data-bottom-top="top:37px;" data-center-top="top[WTF]:25px" alt="Imagem de pastas de arquivos em sequência" class="second"><img src="/assets/icons/folder-yellow.png" alt="Imagem de pastas de arquivos em sequência" class="first"></div>
              <h4>Dados Históricos</h4>
              <p>Tenha acesso ao histórico de posts dos utilizadores e saiba que marcas é que já mencionaram nas redes sociais. Faça buscas retroativas, a partir de 2006, no Twitter.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

app/views/pages/_plans.html.erb
 <section id="plans" class="plans">
      <div class="container">
        <h2 class="section-title">Conheça os nossos <strong>Planos</strong></h2>
        <div class="grid hidden-xs container">
          <div class="item-row"><i class="star"></i></div>
          <div class="item-row"><i class="tag"></i></div>
          <div class="item-row"><i class="people"></i></div>
          <div class="item-row"><i class="chat"></i></div>
          <div class="item-row"><i class="manager"></i></div>
        </div>
        <div class="row">
          <div class="col-sm-3 col-sm-offset-1">
            <div class="plan">
              <h3>Freemium</h3>
              <h2>Use grátis</h2>
              <ul>
                <li><strong>Todas</strong> as funcionalidades</li>
                <li><strong>3</strong> marcas</li>
                <li>Limitado a <strong>1</strong> utilizador</li>
                <li><strong>200</strong> posts por mês</li>
                <li><strong>-</strong></li>
              </ul><a href="https://app.buzzmonitor.com.br/user/signup/new" class="btn" target="_blank"><span>Use grátis</span></a>
            </div>
          </div>
          <div class="col-sm-3 col-sm-offset-1">
            <div class="plan">
              <h3>Saas</h3><small>Pacote mínimo</small>
              <h2 class="value">390<small><strong>€</strong></small><small>/ por mês</small></h2>
              <ul>
                <li><strong>Todas</strong> as funcionalidades</li>
                <li><strong>3</strong> marcas</li>
                <li><strong>3</strong> utilizadores</li>
                <li><strong>5.000</strong> posts por mês</li>
                <li><strong>Setup</strong></li>
              </ul><a href="#proposal" class="btn plan-to-proposal" data-type="saas"><span>PEÇA A SUA PROPOSTA</span></a>
            </div>
          </div>
          <div class="col-sm-3 col-sm-offset-1">
            <div class="plan">
              <h3>SAAS PRO          </h3>
              <h2 class="value">590<small><strong>€</strong></small><small>/ por mês</small></h2>
              <ul>
                <li><strong>Todas</strong> as funcionalidades</li>
                <li><strong>9</strong> marcas</li>
                <li><strong>9</strong> utilizadores</li>
                <li><strong>15.000</strong> posts por mês</li>
                <li><strong>Setup</strong></li>
              </ul><a href="#proposal" class="btn  plan-to-proposal" data-type="saas-pro"><span>PEÇA A SUA PROPOSTA</span></a>
            </div>
          </div>
        </div>
      </div>
    </section>
      <section class="services">
      <div class="container">
        <h2 class="section-title">SERVIÇOS <strong>CORPORATE</strong> </h2>
        <div class="row">
          <div class="col-sm-5 col-sm-offset-1">
            <div class="serv">
              <h3>Hibrid</h3><small>Preços mínimos</small>
              <h2 class="value">890<small><strong>€</strong></small><small>/ por mês</small></h2>
              <p>Análise humana com classificação de depoimentos por assunto (até 8 assuntos) e por sentimento</p>
              <ul>
                <li class="item-row"><i class="star"></i><strong>Todas</strong> as funcionalidades</li>
                <li class="item-row"><i class="tag"></i><strong>3</strong> marcas</li>
                <li class="item-row"><i class="people"></i><strong>9</strong> utilizadores</li>
                <li class="item-row"><i class="chat"></i><strong>5.000</strong> posts por mês</li>
                <li class="item-row"><i class="manager"></i><strong>Setup</strong></li>
              </ul><a href="#proposal" class="btn  plan-to-proposal" data-type="corporate"><span>PEÇA A SUA PROPOSTA</span></a>
            </div>
          </div>
          <div class="col-sm-5">
            <div class="serv">
              <h3>Corporate plus          </h3>
              <h2 class="value"><small>A partir de</small>1500<small> <strong>€</strong>/ por mês</small></h2>
              <p>Análise humana com classificação de depoimentos por assunto e por sentimento, e-mail alerts e reports</p>
              <ul>
                <li><strong>Análise</strong> humana</li>
                <li><strong>Reporting</strong> à medida - diário, semanal ou mensal</li>
                <li><strong>Reports</strong> especiais</li>
                <li><strong>E-mail alerts</strong> com análise humana</li>
                <li><strong>Setup</strong></li>
              </ul><a href="#proposal" class="btn plan-to-proposal" data-type="corporate-plus"><span>PEÇA A SUA PROPOSTA</span></a>
            </div>
          </div>
        </div>
      </div>
    </section>

app/views/pages/_proposal.html.erb
<section id="proposal" class="proposal">
      <div class="container">
        <h2 class="section-title">Peça a sua <strong>Proposta</strong></h2>
        <div class="row">
          <div class="col-sm-5 col-md-4 col-sm-offset-1 col-md-offset-2">
            <p>PEÇA SUA PROPOSTA À E.LIFE - EMPRESA LÍDER EM MONITORIZAÇÃO E GESTÃO DE RELACIONAMENTO NAS REDES SOCIAIS</p>
          </div>
          <div class="col-sm-5 col-md-4">

           <%= render 'partials/proposal' %>
           
          </div>
        </div>
        <p class="call">Ou se preferir, ligue para  <strong>+351 934 698 665</strong></p>
      </div>
    </section>

app/views/pages/_signup.html.erb
<div id="signup-form" class="signup">

<a href="https://app.buzzmonitor.com.br/user/session/new?provider=facebook" class="signfb">Entre com o Facebook  </a>
<a href="https://app.buzzmonitor.com.br/user/session/new?provider=twitter" class="signtw">Entre com o Twitter </a><span>ou        </span>


<%- model_class = User -%>
<%= form_for @user, :url => submit_signup_url, remote: true ,:html => {:class => "form-validate"} do |f| %>
  
  <fieldset>
    <div class="form-group">
      <%= f.label :email, class: 'text-hide' %>
      <%= f.text_field :email,  :class => 'email', required: true, placeholder:  model_class.human_attribute_name(:email) %>
    </div>
    <div class="form-group">
      <%= f.label :password, class: 'text-hide' %>
      <%= f.password_field :password,  :class => '', required: true, placeholder:  model_class.human_attribute_name(:password) %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, class: 'text-hide' %>
      <%= f.password_field :password_confirmation,  :class => '', required: true, placeholder:  model_class.human_attribute_name(:password_confirmation) %>
    </div>
    <% unless !@user_verify_robot %>
      <%= render "partials/recaptcha" %>                  
    <% end %> 
    <%= f.submit t('user.submit_button'), class: "free", disable_with: t('helpers.submit.waiting') %> 
  </fieldset>
<% end %>
</div>

app/views/pages/error_404.html.erb
    <section class="notfound">
      <div class="container">
        <div class="row">
          <div class="col-md-5 col-sm-6">
            <div class="error-tami"></div>
          </div>
          <div class="col-md-5 col-sm-6">
            <h1>Página não encontrada</h1>
            <p>Verifique se a URL foi digitada corretamente ou volte para a <a href="<%= root_url%>">HOME</a></p>
          </div>
        </div>
      </div>
    </section>

app/views/pages/home_a.html.erb
    <section data-speed="3" data-type="background" class="intro">
      <div class="container">
       
        <%= render 'partials/menu_top' %>

        <div class="row">
          <div class="col-sm-7">
            <h1>A nova geração de monitorização das <strong>Redes Sociais</strong></h1>
            <p class="hidden-xs">Monitoring, Social Analytics e Social CRM com mais de mil milhões de dados históricos.</p>
          </div>
          <div class="col-sm-4">
            <%= render 'signup' %>
          </div>
        </div>

        <div class="bookmarks">
          <div class="proposal"><a href="#proposal">Peça <strong>a sua proposta</strong></a></div>
          <div class="social"><a href="https://www.facebook.com/buzzmonitor" target="_blank" class="fb">Facebook</a><a href="https://twitter.com/buzz_monitor" target="_blank" class="tw">Twitter</a><a href="https://www.youtube.com/Buzzmonitor" target="_blank" class="yt">YouTube</a><a href="http://pt.slideshare.net/Elife2009" target="_blank" class="ss">Slideshare</a></div>
        </div>
      </div>
    </section>
    
    <%= render 'know' %>

    <section id="ebooks" class="ebooks">
      <div class="container">
        <h2 class="section-title"> <strong>E.books</strong></h2>
        <h3 class="section-subtitle">Registe-se e faça <span>Download gratuito</span></h3>
        <div class="row">
           <div id="ebook-form">
            <%= render 'ebooks/register' %>
          </div>
        </div>
       
        <div class="row">
          <div class="col-sm-8 col-md-10 col-sm-offset-2 col-md-offset-1">
            <div class="slick">
              <% Ebook.all.each do |ebook| %>
                <div class="slick-slide">
                  
                  <%= link_to download_ebooks_path(ebook.slug), remote: @remote_ebook, :target => "_blank", :class => "link-ebook"  do %>
                    <%= image_tag ebook.imagem.url(:medium), :alt => ebook.titulo %>
                  <% end %>
                </div>
              <% end %> 
            </div>
          </div>
        </div>
      </div>
    </section>
   
    <%= render 'plans' %>
   
    <section id="proposal" class="proposal">
      <div class="container">
        <h2 class="section-title">Peça a sua <strong>Proposta</strong></h2>
        <div class="row">
          <div class="col-sm-5 col-md-4 col-sm-offset-1 col-md-offset-2">
            <p>PEÇA SUA PROPOSTA À E.LIFE - EMPRESA LÍDER EM MONITORIZAÇÃO E GESTÃO DE RELACIONAMENTO NAS REDES SOCIAIS</p>
          </div>
          <div class="col-sm-5 col-md-4">

           <%= render 'partials/proposal' %>
           
          </div>
        </div>
        <p class="call">Ou se preferir, ligue para  <strong>+351 934 698 665</strong></p>
      </div>
    </section>

    <div class="section clients">
      <div class="container">
        <h2 class="section-title">Quem usa o <strong>Buzzmonitor</strong></h2>
        <div class="row">
          <div class="col-xs-6 col-sm-3 col-md-2 col-md-offset-2"><img src="/assets/others/sonae.png" alt="Sonae" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/continente.png" alt="Continente" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/nestle.png" alt="Nestlé" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/galp.png" alt="Galp" class="img-responsive"></div>
        </div>
        <div class="row">
          <div class="col-xs-6 col-sm-3 col-md-2 col-md-offset-2"><img src="/assets/others/phillip-morris.png" alt="Phillip Morris" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/globo.png" alt="Globo" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/ikea.png" alt="IKEA" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/worten.png" alt="Worten" class="img-responsive"></div>
        </div>
      </div>
    </div>
  

app/views/pages/home_b.html.erb
    <section class="video intro">
      <div class="container">
        
        <%= render 'partials/menu_top' %>

        <div class="row">
          <div class="col-sm-5">
            <h1>A nova geração de monitorização das <strong>Redes Sociais</strong></h1>
            <p class="hidden-xs">Monitoring, Social Analytics e Social CRM com mais de mil milhões de dados históricos.</p>
            <%= render 'signup' %>
          </div>
        </div>

        <div class="macbook">
          <div class="video-container">
            <iframe width="770" height="470" src="//www.youtube.com/embed/EqPxZi5fOGQ?rel=0" allowfullscreen></iframe>
          </div>
        </div>
       
        <div class="bookmarks">
          <div class="proposal"><a href="#proposal">Peça <strong>a sua proposta</strong></a></div>
          <div class="social"><a href="https://www.facebook.com/buzzmonitor" target="_blank" class="fb">Facebook</a><a href="https://twitter.com/buzz_monitor" target="_blank" class="tw">Twitter</a><a href="https://www.youtube.com/Buzzmonitor" target="_blank" class="yt">YouTube</a><a href="http://pt.slideshare.net/Elife2009" target="_blank" class="ss">Slideshare</a></div>
        </div>
      </div>
    </section>

    <%= render 'know' %>
    
    <section id="ebooks" class="ebooks-b">
      <div class="container">
        <h2 class="section-title"> <strong>E.books</strong></h2>
        <h3 class="section-subtitle">Registe-se e faça <span>Download gratuito</span></h3>
        <div class="row">
           <div id="ebook-form">
            <%= render 'ebooks/register' %>
          </div>
        </div>
      
        <div id="dg-container-gallery" class="dg-container">
           <div class="dg-wrapper">
              <% Ebook.all.each do |ebook| %>
                 <%= link_to download_ebooks_path(ebook.slug), remote: @remote_ebook, :target => "_blank", :class => "link-ebook"  do %>
                    <%= image_tag ebook.imagem.url(:medium), :alt => ebook.titulo %>
                 <% end %>
              <% end %> 
           </div>
          <nav><span class="dg-prev"></span><span class="dg-next"></span></nav>
        </div>
      </div>
    </section>
    
     <%= render 'plans' %>   
    
    <section id="proposal" class="proposal proposal-b">
      <div class="container">
        <h2 class="section-title">Peça a sua <strong>Proposta</strong></h2>
        <div class="row">
          <div class="col-sm-5 col-md-4 col-sm-offset-1 col-md-offset-2">
            <p>PEÇA SUA PROPOSTA À E.LIFE - EMPRESA LÍDER EM MONITORIZAÇÃO E GESTÃO DE RELACIONAMENTO NAS REDES SOCIAIS</p>
          </div>
          <div class="col-sm-5 col-md-4">

             <div id="proposal-form">
              <%= render 'partials/proposal' %>
            </div>
            
          </div>
          <p class="call-b">Ou se preferir, ligue para  <strong>+351 934 698 665</strong></p>
        </div>
      </div>
    </section>
    <div class="section clients-b">
      <div class="container">
        <h2 class="section-title">Quem usa o <strong>Buzzmonitor</strong></h2>
        <div class="row">
          <div class="col-xs-6 col-sm-3 col-md-2 col-md-offset-2"><img src="/assets/others/sonae.png" alt="Sonae" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/continente.png" alt="Continente" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/nestle.png" alt="Nestlé" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/galp.png" alt="Galp" class="img-responsive"></div>
        </div>
        <div class="row">
          <div class="col-xs-6 col-sm-3 col-md-2 col-md-offset-2"><img src="/assets/others/phillip-morris.png" alt="Phillip Morris" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/globo.png" alt="Globo" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/ikea.png" alt="IKEA" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/worten.png" alt="Worten" class="img-responsive"></div>
        </div>
      </div>
    </div>

app/views/pages/home_c.html.erb
    <section class="wide-video intro">
      <div class="background-video">
        <video autoplay loop class="bgvid">
          <source src="https://s3.amazonaws.com/bm3blog/videos/video.mp4" type="video/mp4">
        </video>
      </div>
      <div class="container">
        <%= render 'partials/menu_top' %>

        <div class="row">
          <div class="col-sm-5">
            <h1>A nova geração de monitoramento das <strong>Redes Sociais</strong></h1>
            <p class="hidden-xs">Monitoramento, Social CRM e Social Analytics <strong>com mais de 1 bilhão de dados históricos</strong></p>
          </div>
          <div class="col-sm-2"><a href="http://www.youtube.com/embed/EqPxZi5fOGQ?autoplay=1&amp;rel=0" class="play fancybox-media">video</a></div>
          <div class="col-sm-4">
            <%= render 'signup' %>
          </div>
        </div>

        <div class="bookmarks">
          <div class="proposal"><a href="#proposal">Peça <strong>a sua proposta</strong></a></div>
          <div class="social"><a href="https://www.facebook.com/buzzmonitor" class="fb">Facebook</a><a href="https://twitter.com/buzz_monitor" class="tw">Twitter</a><a href="https://www.youtube.com/Buzzmonitor" class="yt">YouTube</a><a href="http://pt.slideshare.net/Elife2009" class="ss">Slideshare</a></div>
        </div>
      </div>
    </section>
    
    <%= render 'know' %>
    
    <section id="ebooks" class="ebooks-b">
      <div class="container">
        <h2 class="section-title"> <strong>E.books</strong></h2>
        <h3 class="section-subtitle">Registe-se e faça <span>Download gratuito</span></h3>
        <div class="row">
          <div id="ebook-form">
            <%= render 'ebooks/register' %>
          </div>
          
        </div>
        
         <div id="dg-container" class="dg-container">
           <div class="dg-wrapper">
           <% Ebook.all.each do |ebook| %>
             <%= link_to download_ebooks_path(ebook.slug), remote: @remote_ebook, :target => "_blank", :class => "link-ebook" do %>
                <%= image_tag ebook.imagem.url(:medium), :alt => ebook.titulo %>
             <% end %>
           <% end %> 
           </div>
          <nav><span class="dg-prev"></span><span class="dg-next"></span></nav>
        </div>
      </div>

    </section>

   <%= render 'plans' %>

    <section id="proposal" class="proposal proposal-b">
      <div class="container">
        <h2 class="section-title">Peça a sua <strong>Proposta</strong></h2>
        <div class="row">
          <div class="col-sm-5 col-md-4 col-sm-offset-1 col-md-offset-2">
            <p>PEÇA SUA PROPOSTA À E.LIFE - EMPRESA LÍDER EM MONITORIZAÇÃO E GESTÃO DE RELACIONAMENTO NAS REDES SOCIAIS</p>
          </div>
          <div class="col-sm-5 col-md-4">
            <div id="proposal-form">
              <%= render 'partials/proposal' %>
            </div>
          </div>
          <p class="call-b">Ou se preferir, ligue para  <strong>+351 934 698 665</strong></p>
        </div>
      </div>
    </section>
   <div class="section clients-b">
      <div class="container">
        <h2 class="section-title">Quem usa o <strong>Buzzmonitor</strong></h2>
        <div class="row">
          <div class="col-xs-6 col-sm-3 col-md-2 col-md-offset-2"><img src="/assets/others/sonae.png" alt="Sonae" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/continente.png" alt="Continente" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/nestle.png" alt="Nestlé" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/galp.png" alt="Galp" class="img-responsive"></div>
        </div>
        <div class="row">
          <div class="col-xs-6 col-sm-3 col-md-2 col-md-offset-2"><img src="/assets/others/phillip-morris.png" alt="Phillip Morris" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/globo.png" alt="Globo" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/ikea.png" alt="IKEA" class="img-responsive"></div>
          <div class="col-xs-6 col-sm-3 col-md-2"><img src="/assets/others/worten.png" alt="Worten" class="img-responsive"></div>
        </div>
      </div>
    </div>

app/views/pages/proposal_tks.html.erb
<%= render 'partials/menu_top_internal' %>

<section class="internal">
  <div class="container">
    <h1 class="heading">Proposta</h1>
    <div class="post proposal">
      <div class="row">
        <div class="col-md-6 col-sm-7">
          <div class="judo-tami"></div>
        </div>
        <div class="col-md-6 col-sm-4">
          <div class="content-thanks">
            <h2>PEDIDO ENVIADO COM SUCESSO!</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/submit_newsletter.js.erb
$( document ).ready(function(){
  
  <% if @newsletter.errors.any? %>
     <% @newsletter.errors.full_messages.each do |msg| %>

       $('.notifications').notify({
            type: 'notify',
            message: { text: "<%= j msg %>" },
            closable: false,
            fadeOut: {enabled: true, delay: 3000}
        }).show();

     <% end %>
  <% end %>
  <% if flash[:warning] || flash[:notice] || flash[:alert] || flash[:error] %>

        $('.notifications').notify({
           type: 'notify',
           message: { text: "<%= j flash[:warning] || flash[:notice] || flash[:alert] || flash[:error] %>" },
           closable: false,
           fadeOut: {enabled: true, delay: 3000}
        }).show();
        
  <% end %>

  $("#news-email").val("");

});

app/views/pages/submit_proposal.js.erb
$( document ).ready(function(){

  <% if @proposal.errors.any? %>
     <% @proposal.errors.full_messages.each do |msg| %>
       
           $('.notifications').notify({
               type: 'notify',
               message: { text: "<%= j msg %>" },
               closable: false,
               fadeOut: {enabled: true, delay: 3000}
           }).show();

     <% end %>
     Recaptcha.reload();

  <% else %>

     <% if flash[:warning] || flash[:notice] || flash[:alert] || flash[:error] %>

           $('.notifications').notify({
               type: 'notify',
               message: { text: "<%= j flash[:warning] || flash[:notice] || flash[:alert] || flash[:error] %>" },
               closable: false,
               fadeOut: {enabled: true, delay: 3000}
           }).show();

     <% end %>
     $('#proposal-form').html('<%= j render "partials/proposal" %>');
     proposal_captcha();

     window.location.replace("<%= proposal_tks_url %>");
     
  <% end %>
  
});