config/routes.rb
BuzzmonitorBlogRails::Application.routes.draw do

  match "/404", :to => "pages#error_404"
  
  get "home" => 'pages#home', :as => :home

  get "home_a" => 'pages#home_a', :as => :home_a

  get "home_b" => 'pages#home_b', :as => :home_b

  get "home_c" => 'pages#home_c', :as => :home_c

  get "ebooks/:slug" => 'ebooks#detail', :as => :detail_ebook

  get "ebooks/e/:slug" => 'ebooks#detail', :as => :detail_ebook

  post "ebook_users" => 'ebooks#register', :as =>  :ebook_register

  get "download/:slug" => "ebooks#download", :as => :download_ebooks

  get "ebooks" => "ebooks#index", :as => :ebooks

  get "blog" => "blog#index", :as => :blog

  get "blog/:slug" => "blog#show", :as => :show_blog

  match "artigos" => "artigos#index", :as => :artigos
  
  match "artigos/:slug" => "artigos#show", :as => :artigo

  match "imprensa" => "imprensa#index", :as => :imprensa
  
  match "imprensa/:slug" => "imprensa#show", :as => :show_imprensa

  get "conheca" => 'pages#conheca', :as => :conheca

  get "ebooks/obrigado/:slug" => "ebooks#thankyou", :as => :thankyou_ebooks

  post "submit_proposal" => 'pages#submit_proposal', :as => :submit_proposal

  post "submit_proposal" => 'pages#submit_proposal', :as => :submit_proposal

  post "submit_newsletter" => 'pages#submit_newsletter', :as => :submit_newsletter

  post "submit_signup" => 'users#submit_signup', :as => :submit_signup

  match "proposal_tks" => "pages#proposal_tks", :as => :proposal_tks

  
  get "/" => 'pages#faq', :constraints => { :subdomain => /faq/ }
  
  ActiveAdmin.routes(self)

  devise_config = ActiveAdmin::Devise.config

  devise_config[:controllers][:passwords] = 'passwords'

  devise_for :admin_users, devise_config

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#home'

end

app/controllers/imprensa_controller.rb
class ImprensaController < ApplicationController
  before_filter { |controller| @title = 'Buzzmonitor - Imprensa'}
  before_filter { @proposal_verify_robot = Proposal.verify_robot(request.remote_ip) }

  def index
  	@posts = Post.imprensa.order('publish_date DESC').page(params[:page]).per(10)
  	@posts = @posts.where(:publish_date => Date.parse(params[:date])) unless params[:date].nil?
  	@dias_com_post = Post.imprensa.dias_com_post
    @ranking = Post.imprensa.where("visualizations IS NOT NULL").order('visualizations DESC').limit(5)


    respond_to do |format|
      format.rss { render :layout => false }
      format.html 
    end
  end

  def show
    @post = Post.imprensa.where(:slug => params[:slug]).first
    @posts = Post.imprensa.where(:slug => params[:slug]).page(params[:page]).per(10)

    @dias_com_post = Post.imprensa.dias_com_post
    @ranking = Post.imprensa.where("visualizations IS NOT NULL").order('visualizations DESC').limit(5)

    @post.increment_visualizations
  end
end

app/helpers/imprensa_helper.rb
module ImprensaHelper
end

app/views/imprensa/_sidebar.html.erb
<div class="popular">
    <h2>Artigos <strong>+ populares</strong></h2>
    <ul>
      <% @ranking.each do |post| %>
      <li><%= link_to post.title, show_blog_path(post.slug)%></li>
      <% end %>
    </ul>
  </div>



  <div id="calendar" class="responsive-calendar">
    <div class="controls"><a data-go="prev" class="pull-left"><i class="glyphicon glyphicon-circle-arrow-left"></i></a>
      <h4><span data-head-month></span><span data-head-year></span></h4><a data-go="next" class="pull-right"><i class="glyphicon glyphicon-circle-arrow-right"></i></a>
    </div>
    <div class="day-headers">
      <div class="day header">Dom</div>
      <div class="day header">Seg</div>
      <div class="day header">Ter</div>
      <div class="day header">Qua</div>
      <div class="day header">Qui</div>
      <div class="day header">Sex</div>
      <div class="day header">Sab</div>
    </div>
    <div data-group="days" class="days"></div>
  </div>
</div>


<script type="text/javascript">
  
  $( document ).ready(function(){


  var date = new Date();
  var d = date.getDate();
  var m = date.getMonth() + 1;
  var y = date.getFullYear();

  $(".responsive-calendar").responsiveCalendar({
    time: y +'-'+ m,
    translateMonths: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
    allRows : false,
      events: {
        <% @dias_com_post.each do |data| %>
        "<%= data.strftime('%Y-%m-%d')%>": {"class": "active special", "url": "<%= root_url %>blog?date=<%= data.strftime('%Y-%m-%d')%>"},
        <% end %>
      }
    });

  });


</script>

app/views/imprensa/index.html.erb
<%= render 'partials/menu_top_internal' %>

<section class="internal">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <h1 class="heading">Imprensa</h1>
            <% @posts.each do |post| %>

            <div class="post">

            	<span class="post-date"><%= l post.publish_date %></span>
            	<span class="reading-time">Tempo estimado de leitura <%= ActionView::Base.full_sanitizer.sanitize(post.body).reading_time %> <i class="glyphicon glyphicon-time"></i></span>
             
            	<h2 class="post-heading">
            		<%= link_to post.title, show_imprensa_path(post.slug)%>
            	</h2>

             
            	<%=	raw post.body %>

              <div class="share">
                <%= compartilhamentos url: show_imprensa_path(post.slug, :only_path => false), title: post.title, minified_url: post.minified_url %>
              </div>
            </div>

            <% end %>

            
            <div class="text-center">
            	<%= paginate @posts %>
            </div>
          </div>
          <div class="col-md-4">
            <%= render 'sidebar' %>
        </div>
      </div>
    </section>



<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=462545467122188";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/imprensa/show.html.erb
<%= render 'partials/menu_top_internal' %>

<section class="internal">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <h1 class="heading interna">Imprensa</h1>
          
          	<div class="back"><span class="line"></span><%= link_to 'Voltar', imprensa_path %></div>

            <div class="post">

            	<span class="post-date"><%= l @post.publish_date %></span>
            	<span class="reading-time">Tempo estimado de leitura <%= ActionView::Base.full_sanitizer.sanitize(@post.body).reading_time %> <i class="glyphicon glyphicon-time"></i></span>
             
            	<h2 class="post-heading">
            		<%= link_to @post.title, show_imprensa_path(@post.slug)%>
            	</h2>

              <h3 class="sub-heading">
                <%= @post.subtitle %>
              </h3>

            	<%=	raw @post.body %>

              <div class="share">
                <%= compartilhamentos url: show_imprensa_path(@post.slug, :only_path => false), title: @post.title, minified_url: @post.minified_url %>
              </div>
              <div class="free"><a href="https://app.buzzmonitor.com.br/user/signup/new" target="_blank">Use grátis</a></div>
            </div>

         
            
            <div class="text-center">
            	<%= paginate @posts %>
            </div>
          </div>
          <div class="col-md-4">
            <%= render 'sidebar' %>
        </div>
      </div>
    </section>



<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=462545467122188";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>