config/routes.rb
BuzzmonitorBlogRails::Application.routes.draw do

  match "/404", :to => "pages#error_404"
  
  get "home" => 'pages#home', :as => :home

  get "home_a" => 'pages#home_a', :as => :home_a

  get "home_b" => 'pages#home_b', :as => :home_b

  get "home_c" => 'pages#home_c', :as => :home_c

  get "ebooks/:slug" => 'ebooks#detail', :as => :detail_ebook

  get "ebooks/e/:slug" => 'ebooks#detail', :as => :detail_ebook

  post "ebook_users" => 'ebooks#register', :as =>  :ebook_register

  get "download/:slug" => "ebooks#download", :as => :download_ebooks

  get "ebooks" => "ebooks#index", :as => :ebooks

  get "blog" => "blog#index", :as => :blog

  get "blog/:slug" => "blog#show", :as => :show_blog

  match "artigos" => "artigos#index", :as => :artigos
  
  match "artigos/:slug" => "artigos#show", :as => :artigo

  match "imprensa" => "imprensa#index", :as => :imprensa
  
  match "imprensa/:slug" => "imprensa#show", :as => :show_imprensa

  get "conheca" => 'pages#conheca', :as => :conheca

  get "ebooks/obrigado/:slug" => "ebooks#thankyou", :as => :thankyou_ebooks

  post "submit_proposal" => 'pages#submit_proposal', :as => :submit_proposal

  post "submit_proposal" => 'pages#submit_proposal', :as => :submit_proposal

  post "submit_newsletter" => 'pages#submit_newsletter', :as => :submit_newsletter

  post "submit_signup" => 'users#submit_signup', :as => :submit_signup

  match "proposal_tks" => "pages#proposal_tks", :as => :proposal_tks

  
  get "/" => 'pages#faq', :constraints => { :subdomain => /faq/ }
  
  ActiveAdmin.routes(self)

  devise_config = ActiveAdmin::Devise.config

  devise_config[:controllers][:passwords] = 'passwords'

  devise_for :admin_users, devise_config

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#home'

end

app/models/ebook.rb
class Ebook < ActiveRecord::Base
  attr_accessible :data, :imagem, :link, :texto, :titulo, :slug, :pdf

has_attached_file :imagem, :styles => {:home => '153x216#', :medium => '255x355#'},
    :path           => "#{ENV['s3_root']}/:attachment/:id/:style.:extension",
    :storage        => :s3,
    :bucket            => ENV['s3_bucket'],
    :s3_credentials => {
        :access_key_id     => ENV['s3_access_key_id'],
        :secret_access_key => ENV['s3_secret_access_key']
    }  
   
has_attached_file :pdf,
    :path           => "#{ENV['s3_root']}/:attachment/:id/:style.:extension",
    :storage        => :s3,
    :bucket            => ENV['s3_bucket'],
    :s3_credentials => {
        :access_key_id     => ENV['s3_access_key_id'],
        :secret_access_key => ENV['s3_secret_access_key']
    }   
    after_create :generate_minified_url

	def self.dias_com_post
    	self.order('data DESC').uniq.pluck(:data)
  	end

  	def minified_url
    if read_attribute(:minified_url).nil? || read_attribute(:minified_url) == 'error: No operations allowed after connection closed.'
      generate_minified_url
    end
    
    read_attribute(:minified_url)
  end

  private

  def generate_minified_url
      url = "http://www.buzzmonitor.pt/ebooks/e/" +  URI::escape(self.slug)
      uri = URI.parse("http://zi.cx/_ws/shorten?key=zAtAmexezeqaTRaGapHEc4TaDaZESEsT&address=#{url}&tag=qualquer&type=text")

      # Shortcut
      response = Net::HTTP.get_response(uri)

      # Will print response.body
      Net::HTTP.get_print(uri)

      # Full
      http = Net::HTTP.new(uri.host, uri.port)
      response = http.request(Net::HTTP::Get.new(uri.request_uri))

      update_attribute(:minified_url, response.body.strip)
  end


end

app/controllers/ebooks_controller.rb
# encoding: UTF-8
class EbooksController < ApplicationController
 before_filter { |controller| @title = 'Buzzmonitor - E-books'}
 before_filter :list_ebooks, :only => [:index, :register]
  
  def index
    @ebook_user = EbookUser.new
  end

  def show
    redirect_to ebooks_path
  end

  def download
  	@ebook = Ebook.find_by_slug(params[:slug]);

    unless cookies[:ebook_user].blank?
      @ebook_user = EbookUser.find(cookies[:ebook_user])

      unless @ebook_user.nil?
        @ebook_user.ebook = @ebook

        begin
          highrise(@ebook_user, 'EBOOK_PORTUGAL_' + @ebook.slug)
        rescue Exception => msg  
          ErrorMailer.notification_error(t('highrise.error_subject') + msg.inspect, @ebook_user).deliver
        end
        flash[:notice] = t('ebook.waiting')
      end
    end

    respond_to do |format|
      format.js 
      format.html { redirect_to thankyou_ebooks_url(@ebook.slug) }
    end
  end



  def detail
    @ebook = Ebook.find_by_slug(params[:slug]);
    @ebook_user = EbookUser.new

    if @ebook.nil?
      flash[:notice] = 'Ebook não encontrado.'
      redirect_to ebooks_url
    end

  end

  def register
    @ebook = nil
    @ebook_user = EbookUser.new(params[:ebook_user])
    @ebook = Ebook.find(@ebook_user.ebook_id) unless @ebook_user.ebook_id.nil?

    if @ebook_verify_robot
      @ebook_user.captcha = recaptcha()
      @ebook_user.flag_captcha  = true
    else
      @ebook_user.captcha = true
      @ebook_user.flag_captcha  = false
    end
    @ebook_user.ip = request.remote_ip


    respond_to do |format|
      if @ebook_user.save 

        begin
          if @ebook_user.accept_newsletter
            mailchimp(@ebook_user, t('mailchimp.default_list') )
          end
        rescue Exception => msg  
          ErrorMailer.notification_error(t('mailchimp.error_subject') + msg.inspect, @ebook_user).deliver
        end

        begin
          tags = ['buzzmonitor','bm-pt','EBOOK_PORTUGAL']
          if @ebook_user.accept_proposal == true
            tags << 'proposta-pt'
          end
          highrise(@ebook_user, tags)
        rescue Exception => msg  
          ErrorMailer.notification_error(t('highrise.error_subject') + msg.inspect, @ebook_user).deliver
        end

        EbookMailer.notification(@ebook_user).deliver
        flash[:notice] = t('ebook.success')
        cookies[:ebook_user] = @ebook_user.id

        format.js 
      else
        format.js
      end
    end


  end


  def thankyou
    @ebook = Ebook.find_by_slug(params[:slug]);
    if @ebook.nil?
      flash[:notice] = 'Ebook não encontrado.'
      redirect_to ebooks_url 
    end

    unless cookies[:ebook_user].blank?
        @ebook_user = EbookUser.find(cookies[:ebook_user])

      unless @ebook_user.nil?
          @ebook_user.ebook = @ebook
        begin
          tags = ['buzzmonitor','bm-pt','ebook']
          tags << @ebook.slug
          highrise(@ebook_user, tags) 
        rescue Exception => msg  
          logger.debug("#DEBUG EBOOK: " + msg.inspect)
          ErrorMailer.notification_error( t('highrise.error_subject') + msg.inspect, @ebook_user).deliver
        end
        EbookMailer.notification(@ebook_user).deliver
      end
    end

  end


  private

  def list_ebooks
    @ebooks = Ebook.order('data DESC')
  end


  


end

app/helpers/ebooks_helper.rb
module EbooksHelper
end

app/views/ebooks/_download.html.erb
<%= form_tag  thankyou_ebooks_path(@ebook.slug),  method: 'get' do |f| %>
	<input type="submit" value="<%= t 'ebook.download_button' %>" class="btn download"></fieldset>
<% end %>

app/views/ebooks/_register.html.erb
<% if cookies[:ebook_user].blank?  %>

  <%- model_class = EbookUser -%>
  <%= form_for(@ebook_user, :url => ebook_register_url, remote: true, :html => { :class => 'ebooks-form validate-form'} ) do |f| %>
   
    <fieldset>
      <div class="col-sm-<%= @ebook_verify_robot ? 4 : 6 %>">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, id: 'name', class: '', placeholder: model_class.human_attribute_name(:name) %>
        </div>
        <div class="form-group">
          <%= f.label :company %>
          <%= f.text_field :company, id: 'company', class: '', placeholder: model_class.human_attribute_name(:company) %>
        </div>
      </div>
      <div class="col-sm-<%= @ebook_verify_robot ? 4 : 6 %>">
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, id: 'email', class: 'required', placeholder: model_class.human_attribute_name(:email)  %>
        </div>
        <div class="form-group">
          <%= f.label :phone %>
          <%= f.text_field :phone, id: 'phone', class: '', placeholder: model_class.human_attribute_name(:phone) %>
        </div>
        <div class="checkbox-inline">
          <label for="news"><%= f.check_box :accept_newsletter, :id => 'accept', :checked => true  %><%= model_class.human_attribute_name(:accept_newsletter) %></label>
        </div>
      <!--   <div class="checkbox-inline">
          <label for="proposta"><%= f.check_box :accept_proposal, :id => 'accept', :checked => true  %><%= model_class.human_attribute_name(:accept_proposal) %></label>
        </div> -->
      </div>
      <% unless !@ebook_verify_robot %>
      <div class="col-sm-4">
         
           <script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>
            <div id="ebook-captcha" class="recaptcha_widget">
              <div class="container-captcha" id="recaptcha_widget_ebook">
                <div class="imagem" id="recaptcha_image">
                </div>
                <div class="recaptcha_input">
                  <label for="recaptcha_response_field" class="recaptcha_only_if_image"><%= t "recaptcha.recaptcha_only_if_image" %>:</label>
                  <label for="recaptcha_response_field" class="recaptcha_only_if_audio"><%= t "recaptcha.recaptcha_only_if_audio" %>:</label>
                  <input id="recaptcha_response_field" type="text" name="recaptcha_response_field">
                </div>
                 <ul class="recaptcha_options">
                  <li><a href="javascript:Recaptcha.reload()"><i class="glyphicon glyphicon-refresh"></i><span class="captcha_hide">Outro CAPTCHA</span></a></li>
                  <li class="recaptcha_only_if_image"><a href="javascript:Recaptcha.switch_type('audio')"><i class="glyphicon glyphicon-volume-up"></i><span class="captcha_hide">CAPTCHA com audio</span></a></li>
                  <li class="recaptcha_only_if_audio"><a href="javascript:Recaptcha.switch_type('image')"><i class="glyphicon glyphicon-picture"></i><span class="captcha_hide">CAPTCHA com imagem</span></a></li>
                  <li><a href="javascript:Recaptcha.showhelp()"><i class="glyphicon glyphicon-question-sign"></i><span class="captcha_hide">Ajuda</span></a></li>
                </ul>
              </div>
            </div>
      </div>
       <% end %>
      <div class="col-sm-2 col-sm-offset-5">
        <%= f.submit t('ebook.register_button'), disable_with: t('helpers.submit.waiting') %> 
      </div>
    </fieldset>
  <% end %>

<% end %>

app/views/ebooks/detail.html.erb
<%= render 'partials/menu_top_internal' %>

<%- model_class = EbookUser -%>
<section class="internal">
      <div class="container">
        <h1 class="heading">E-books</h1>
        <div class="post ebook"><span class="post-date"><%= l @ebook.data unless @ebook.data.nil? %></span>
          <div class="row">
            <div class="col-md-3 col-sm-4">
                <img src="<%= @ebook.imagem.url %>" class="img-responsive">
                
                <%= render 'download' unless cookies[:ebook_user].blank? %>

            </div>
            <div class="col-md-<%= cookies[:ebook_user].blank? ? 4 : 8  %> col-sm-7">
              <h2><%= @ebook.titulo %></h2>
              <p><%= raw @ebook.texto %></p>
            </div>

            <% if cookies[:ebook_user].blank?  %>
            
                <div class="col-md-4 col-md-offset-1">
                  <%= form_for(@ebook_user, :url => ebook_register_url, remote: true, :html => { :class => 'ebooks-form validate-form'} ) do |f| %>
                    <%= f.hidden_field :ebook_id, :value => @ebook.id  %>
                    <h3>Cadastre-se para baixar os papers</h3>
                    <fieldset>
                      <div class="form-group">
                         <%= f.label :name %>
                        <%= f.text_field :name, id: 'name', class: '', placeholder: model_class.human_attribute_name(:name) %>
                      </div>
                      <div class="form-group">
                        <%= f.label :email %>
                        <%= f.text_field :email, id: 'email', class: 'required', placeholder: model_class.human_attribute_name(:email)  %>
                      </div>
                      <div class="form-group">
                        <%= f.label :company %>
                        <%= f.text_field :company, id: 'company', class: '', placeholder: model_class.human_attribute_name(:company) %>
                      </div>
                      <div class="form-group">
                        <%= f.label :phone %>
                        <%= f.text_field :phone, id: 'phone', class: '', placeholder: model_class.human_attribute_name(:phone) %>
                      </div>
                      <div class="checkbox">
                        <label for="news"><%= f.check_box :accept_newsletter, :id => 'accept', :checked => true  %><%= model_class.human_attribute_name(:accept_newsletter) %></label>
                      </div>
                      <div class="checkbox">
                        <label for="propose"><%= f.check_box :accept_proposal, :id => 'accept', :checked => true  %><%= model_class.human_attribute_name(:accept_proposal) %></label>
                      </div>
                      
                      <% if @ebook_verify_robot %>
                      
                           <script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>
                            <div id="ebook-captcha" class="recaptcha_widget">
                              <div class="container-captcha" id="recaptcha_widget_ebook">
                                <div class="imagem" id="recaptcha_image">
                                </div>
                                <div class="recaptcha_input">
                                  <label for="recaptcha_response_field" class="recaptcha_only_if_image"><%= t "recaptcha.recaptcha_only_if_image" %>:</label>
                                  <label for="recaptcha_response_field" class="recaptcha_only_if_audio"><%= t "recaptcha.recaptcha_only_if_audio" %>:</label>
                                  <input id="recaptcha_response_field" type="text" name="recaptcha_response_field">
                                </div>
                                 <ul class="recaptcha_options">
                                  <li><a href="javascript:Recaptcha.reload()"><i class="glyphicon glyphicon-refresh"></i><span class="captcha_hide">Outro CAPTCHA</span></a></li>
                                  <li class="recaptcha_only_if_image"><a href="javascript:Recaptcha.switch_type('audio')"><i class="glyphicon glyphicon-volume-up"></i><span class="captcha_hide">CAPTCHA com audio</span></a></li>
                                  <li class="recaptcha_only_if_audio"><a href="javascript:Recaptcha.switch_type('image')"><i class="glyphicon glyphicon-picture"></i><span class="captcha_hide">CAPTCHA com imagem</span></a></li>
                                  <li><a href="javascript:Recaptcha.showhelp()"><i class="glyphicon glyphicon-question-sign"></i><span class="captcha_hide">Ajuda</span></a></li>
                                </ul>
                              </div>
                            </div>
                     
                        <% end %>
                        <%= f.submit t('ebook.register_button'), disable_with: t('helpers.submit.waiting') %> 
                    </fieldset>
                  <% end %>
                </div>
            <% end %>

          </div>
        </div>
      </div>
    </section>

app/views/ebooks/download.js.erb
<% if cookies[:ebook_user].blank? %>
    $('.notifications').notify({
      type: 'notify',
      message: { text: "<%= j t('ebook.you_need_register') %>" },
      closable: false,
      fadeOut: {enabled: true, delay: 3000}
    }).show();

    $('a[href=#ebooks]').trigger('click');
      
<% else %>

    <% if flash[:warning] || flash[:notice] || flash[:alert] || flash[:error] %>
      
      $('.notifications').notify({
        type: 'notify',
        message: { text: "<%= j flash[:warning] || flash[:notice] || flash[:alert] || flash[:error] %>" },
        closable: false,
        fadeOut: {enabled: true, delay: 3000}
      }).show();

    <% end %>

  <% unless @ebook.nil? %>
    window.location = "<%= j thankyou_ebooks_url(@ebook.slug) %>";
  <% end %>
    
<% end %>

app/views/ebooks/index.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=462545467122188";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<!-- .line-b -->
        <div class="line-b">
            <!-- .main-content -->
            <div class="main-content interna">
                    <h1 class="heading">Ebooks</h1>
                    <% if cookies[:ebook_user].blank?  %>
                    <%- model_class = EbookUser -%>
                    <div class="col-4">
                    <%= form_for(@ebook_user, :html => { :class => 'horizontal-form ebooks-form-index form-validate-default'} ) do |f| %>

                        

                        <fieldset>
                            <h3><%= t 'ebook.title_register' %></h3>

                             <% if @ebook_user.errors.any? %>
                              <div class="alert error">
                              <i class="exclamation"></i>
                                  <ul>
                                    <% @ebook_user.errors.full_messages.each do |msg| %>
                                    <li><%= msg %></li>
                                    <% end %>
                                  </ul>
                              </div>
                            <% end %>


                            <div class="col-one">
                                <%= f.text_field :name, id: 'name', class: '', placeholder: model_class.human_attribute_name(:name) %>
                                <%= f.text_field :email, id: 'email', class: 'required', placeholder: model_class.human_attribute_name(:email)  %>
                            </div>
                            <!-- /.col-one -->
                            <div class="col-two">
                                <%= f.text_field :company, id: 'company', class: '', placeholder: model_class.human_attribute_name(:company) %>
                                 <%= f.text_field :phone, id: 'phone', class: '', placeholder: model_class.human_attribute_name(:phone) %>
                            </div>
                            <!-- /.col-two -->
                            <div class="col-three">
                                <input type="submit" alt="" value="<%= t 'ebook.register_button' %>">
                            </div>
                            <!-- /.col-three -->
                            <label for="news" class="check-news"><%= f.check_box :accept_newsletter, :id => 'news', :checked => true  %> <%= model_class.human_attribute_name(:accept_newsletter) %></label>
                            <label for="proposal" class="check-news"><%= f.check_box :accept_proposal, :id => 'accept', :checked => true  %><%= model_class.human_attribute_name(:accept_proposal) %></label>
                        </fieldset>

                        <% unless !@ebook_verify_robot %>
                            <script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>
                            <div id="ebook-user-captcha"  class="recaptcha">
                                <div id="recaptcha_widget" class="container">
                                    <div class="imagem" id="recaptcha_image" ></div>
                                    <input type="text" name="recaptcha_response_field" id="recaptcha_response_field">
                                    <a href="javascript:Recaptcha.reload()" class="reload" id="reload-button">Reload</a>
                                </div>
                                <h2><%= t 'ebook.recaptcha_title' %></h2>
                                <p><%= t 'ebook.recaptcha_text' %></p>
                            </div>
                        <% end %>

                    <% end %>
                    <!-- /.horizontal-form -->


                   

                    <% end %>

                    <div class="books-container">
                    <% @ebooks.each do |ebook| %>
                        <div class="book">
                            <a href="<%= detail_ebook_path(ebook.slug) %>"><img src="<%= ebook.imagem %>" alt=""></a>
                            <p class="description"><%= ebook.titulo %></p>
                            <% unless ebook.pdf.blank? %>
                            <% unless cookies[:ebook_user].blank? %>
                                <a href="<%= thankyou_ebooks_path(ebook.slug) %>" class="actions save"><span>Download</span></a> 
                            <% else %>
                                <a href="<%= download_ebooks_path(ebook.slug) %>" class="actions save"><span>Download</span></a>
                            <% end %>
                                <a href="<%= detail_ebook_path(ebook.slug) %>" target="_blank" class="actions plus"><span>Mais</span></a> 
                            <% end %>
                        </div>
                    <% end %>    
                    </div>
                
            </div>
            <!-- /.main-content -->
        </div>
        <!-- /.line-b -->

app/views/ebooks/register.js.erb
<% if @ebook_user.errors.any? %>
   <% @ebook_user.errors.full_messages.each do |msg| %>
    
        $('.notifications').notify({
          type: 'notify',
          message: { text: "<%= j msg %>" },
          closable: false,
          fadeOut: {enabled: true, delay: 3000}
        }).show();

   <% end %>
   Recaptcha.reload();
<% else %>

   $('#ebook-form').fadeOut(function(){
      <% if flash[:warning] || flash[:notice] || flash[:alert] || flash[:error] %>
        
        $('.notifications').notify({
          type: 'notify',
          message: { text: "<%= j flash[:warning] || flash[:notice] || flash[:alert] || flash[:error] %>" },
          closable: false,
          fadeOut: {enabled: true, delay: 3000}
        }).show();

      <% end %>
   });
   $(".link-ebook").removeAttr("data-remote");

   $('#ebook-form').html('<%= j render "register" %>');
    ebook_captcha();

  <% unless @ebook.nil? %>
    window.location = "<%= detail_ebook_path(@ebook.slug) %>";
  <% end %>
    
<% end %>

app/views/ebooks/thankyou.html.erb
<%= render 'partials/menu_top_internal' %>

   <section class="internal">
      <div class="container">
        <h1 class="heading">E-books</h1>
        <div class="post ebook">
          <div class="row">
            <div class="col-md-6 col-sm-7">
              <div class="judo-tami"></div>
            </div>
            <div class="col-md-4 col-sm-4">
              <div class="content-thanks">
                <h2><%= t 'ebook.thanks' %></h2>
                <h3><%= t 'ebook.yout_download_start_in_seconds' %></h3>
                <p><%= t 'ebook.if_you_have_problem' %>, <%= link_to t('ebook.click_here'), download_ebooks_path(params[:slug]), :taget => '_blank' %></p>
                <p><%= t('ebook.go_back_to')%> <%= link_to 'HOME', root_url %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

<script>
  $(document).ready(function(){
     setTimeout(function(){ window.location = "<%= @ebook.pdf.to_s %>"; },4000);
  });
</script>